extra_reports:
  - title: "Artificial Intelligence in Telecommunications (WEF 2025)"
    url: "https://reports.weforum.org/docs/WEF_Artificial_Intelligence_in_Telecommunications_2025.pdf"
    date: "2025-11-15"
  - title: "Artificial Intelligence Index Report 2025"
    url: "https://hai-production.s3.amazonaws.com/files/hai_ai_index_report_2025.pdf"
    date: "2025-10-18"
  - title: "AI Industry Landscape Report 2025"
    url: "https://repository.ceibs.edu/files/59116885/AI_Industry_landscape_report_2025.pdf"
    date: "2025-11-01"
  - title: "Intelligence Report on Quantum Diplomacy in Action 2025–2026"
    url: "https://open-quantum-institute.cern/wp-content/uploads/2025/11/Intelligence-Report-2025.pdf"
    date: "2025-11-01"
  - title: "2025 Global Quantum Computing Industry Outlook"
    url: "https://icvtank.oss-ap-southeast-1.aliyuncs.com/QUANTUM-REPORTS/2025%20Global%20Quantum%20Computing%20Industry%20Development%20Prospect.pdf"
    date: "2025-10-20"
  - title: "Industry Outlook 2025 – Tech & Space (EIU)"
    url: "https://argaamplus.s3.amazonaws.com/b3cd580a-3656-44ed-838a-5f2996ff6fc9.pdf"
    date: "2025-11-10"
  - title: "Global Banking Industry Outlook 2025"
    url: "https://pic.bankofchina.com/bocappd/rareport/202504/P020250428553809527239.pdf"
    date: "2025-10-27"
  - title: "Digital Progress and Inclusive Growth – World Bank 2025"
    url: "https://openknowledge.worldbank.org/server/api/core/bitstreams/dccd113e-3ce6-4442-ac35-bc4a5a205ee2/content"
    date: "2025-12-10"
